### ISSUE TITLE
Addition of code formatting check in CI 

### ISSUE THREAD

**Issue by alanssitis** [Autonomous-Motorsports-Purdue/AMP_ASSv2#18]
## Description
Implement a CI action checking whether code base is formatted according to specifications to be determined

## Sub-tasks
-[] TBD

## Resources
* https://moveit.ros.org/documentation/contributing/code/

**Comment by RishiKumarRay** [comment]
which formatting tool you want use?

**Comment by alanssitis** [comment]
Hi @RishiKumarRay, at this point we don't know yet. I have only done skimming on possible auto-formaters. I haven't found one for ROS projects yet, and if such doesn't exist I think the best path forward is using language-specific formatters (e.g. autopep8 for python and clang-format). Right now this issue is still being researched and developed but all recommendations are welcome!

**Comment by alanssitis** [comment]
By the way, are you a member of AMP?

**Comment by RishiKumarRay** [comment]
@alanssitis No, I am not , whats that?

**Comment by zghera** [comment]
@RishiKumarRay Autonomous Motorsports Purdue. We are an organization at Purdue University. At this time, we are only accepting contributions from members of the club.
