### ISSUE TITLE
SLAM Strategy with Loop Closing Capability

### ISSUE THREAD

**Issue by zghera** [Autonomous-Motorsports-Purdue/AMP_ASSv2#2]
## Description
... Will update soon ...

In the meantime, for background please see Autonomous-Motorsports-Purdue/AMP_ASSv1#18 ...

## Sub-tasks
- [ ] ...
- [ ] Make sure your code follows the [style guide](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv2/wiki/Software-Style-Guide).

## Other Useful Information
* ...

**Comment by Reschivon** [comment]
Closed -- we will try to implement RTabMap with the ZED2 camera for our SLAM strategy, which spans multiple issues
